config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create] do
    member do
      post '/upvote', action: 'upvote'
      post '/downvote', action: 'downvote'
    end
  end

  resources :posts

  post '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote_post'
  post '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote_post'

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users, only: [:new, :create] do
    collection do
      post '/follow/:user_id', action: :follow, as: 'follow'
      post '/unfollow/:user_id', action: :unfollow, as: 'unfollow'
    end
  end

  scope 'u', as: 'public_users' do
    get '/:id', to: 'users#show'
  end

  root 'posts#index'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  post_id    :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :post

  validates_presence_of :body
  validates_presence_of :post
  validates_presence_of :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include VotableAction

  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        CommentEmailJob.perform_later @comment
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row comment" data-id="<%= comment.id %>">

  <div class="col-md-12">

    <div class="row">

      <div class="col-md-1">
        <%= gravatar_for comment.user, {size: 30} %>
      </div>

      <div class="col-md-7">
        <div class="row">

          <div class="col-md-12">
            <%= comment.user.full_name %>
          </div>

        </div>

        <div class="row">

          <div class="col-md-12">
            <%= comment.body %>
          </div>

        </div>
      </div>

      <div class="col-md-1">
        <%= button_to '+', upvote_comment_path(comment), remote: true, class: 'upvote-button btn btn-success form-control' %>
      </div>

      <div class="col-md-2">
        <h4>Votes <span class="vote-count"><%= comment.votes.count %></span></h4>
      </div>

      <div class="col-md-1">
        <%= button_to '-', downvote_comment_path(comment), remote: true, class: 'downvote-button btn btn-danger form-control' %>
      </div>
    </div>

  </div>

</div>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row comment-form">
      <div class="col-md-10">
        <%= f.text_area :body, class: 'form-control' %>
        <%= f.hidden_field :post_id, value: post.id %>
      </div>

      <div class="col-md-2">
        <%= f.submit 'Add Comment', class: 'btn btn-success form-control' %>
      </div>
    </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/upvote.js.erb
/**
 * Created by danielward on 6/23/15.
 */

$('div[data-id="<%= @entity.id %>"].comment span.vote-count').text('<%= escape_javascript(@entity.votes.count.to_s) %>');

//$('#comments').empty();
//$('#comments').append('<%= escape_javascript(render partial: 'comments/comment', collection: @entity.post.comments_sorted_by_votes) %>')