config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create] do
    member do
      post '/upvote', action: 'upvote'
      post '/downvote', action: 'downvote'
    end
  end

  resources :posts

  post '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote_post'
  post '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote_post'

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users, only: [:new, :create] do
    collection do
      post '/follow/:user_id', action: :follow, as: 'follow'
      post '/unfollow/:user_id', action: :unfollow, as: 'unfollow'
    end
  end

  scope 'u', as: 'public_users' do
    get '/:id', to: 'users#show'
  end

  root 'posts#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :comments
  has_many :votes

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy

  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following, through: :active_relationships, source: :followed

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email

  validates_format_of :email, with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]+\z/

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def abbreviated_name
    self.first_name[0].upcase + '. ' + self.last_name
  end

  def feed
    Post.where('user_id = ? OR user_id IN (?)', self.id, self.following.ids).order('created_at DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        SignupEmailJob.perform_later @user

        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    Relationship.create!(follower: current_user, followed: @user)
  end

  def unfollow
    Relationship.where(follower: current_user, followed: @user).first.try(:destroy!)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id] || params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  #
  # @param [User] user
  # @param [Hash] options
  def gravatar_for(user, options = {})
    options = {
        size: '200',
        default_icon: 'identicon',
        rating: 'pg'
    }.deep_merge(options)

    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?r=#{options[:rating]}&s=#{options[:size]}&d=#{options[:default_icon]}"
    link_to image_tag(gravatar_url, alt: user.first_name, class: "gravatar"), public_users_path(user)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-4 col-xs-offset-4">
    <%= f.text_field :first_name, class: 'form-control', placeholder:  'First Name' %>
  </div>
  <div class="form-group col-xs-4 col-xs-offset-4">
    <%= f.text_field :last_name, class: 'form-control', placeholder:  'Last Name' %>
  </div>
  <div class="form-group col-xs-4 col-xs-offset-4">
    <%= f.text_field :email, class: 'form-control', placeholder:  'Email' %>
  </div>
  <div class="form-group col-xs-4 col-xs-offset-4">
    <%= f.password_field :password, class: 'form-control', placeholder:  'Passsword' %>
  </div>

  <div class="form-group col-xs-4 col-xs-offset-4">
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder:  'Confirmation' %>
  </div>

  <div class="form-group col-xs-4 col-xs-offset-4">
    <%= f.submit 'Create' , class: 'form-control btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/follow.js.erb
$('.follow-button').hide();
$('.unfollow-button').show();

$('.followers-count').text(<%= escape_javascript @user.followers.count.to_s %>);

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="text-center">New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <% if current_user && @user.id == current_user.id %>
      <div class="row">
        <div class="col-md-12">
          <h3 style="color:darkred">It's You!!!!</h3>
        </div>
      </div>
  <% end %>

  <div class="row">

    <!-- Main Column 1-->

    <div class="col-md-3">

      <div class="row">

        <div class="col-md-12">
          <h3><%= @user.abbreviated_name %></h3>
        </div>

      </div>

      <div class="row">

        <div class="col-md-12 gravatar-container">
          <%= gravatar_for(@user, size: '300') %>
        </div>

      </div>

      <div class="row">

        <div class="col-md-6 text-center">
          <h4>Followers</h4>
          <h5 class="followers-count"><%= @user.followers.count %></h5>
        </div>

        <div class="col-md-6 text-center">
          <h4>Following</h4>
          <h5><%= @user.following.count %></h5>
        </div>

      </div>

      <% if current_user && @user.id != current_user.id %>
          <% is_following = current_user.following.include?(@user)  %>
              <div class="row unfollow-button" style="display: <%= is_following ? 'block' : 'none'  %>">
                <div class="col-md-12">
                  <%= button_to 'Unfollow', unfollow_users_path(user_id: @user.id), remote: true, class: 'btn btn-danger form-control' %>
                </div>
              </div>

              <div class="row follow-button" style="display: <%= !is_following ? 'block' : 'none' %>">
                <div class="col-md-12">
                  <%= button_to 'Follow', follow_users_path(user_id: @user.id),  remote: true, class: 'btn btn-success form-control' %>
                </div>
              </div>
      <% end %>

    </div>

    <!-- Main Column 2-->

    <div class="col-md-9">

      <div class="col-md-12">

        <div class="row">
          <div class="col-md-12 text-center">
            <h3>Posts</h3>
          </div>
        </div>

        <div class="row" id="post_container">
          <% if @user.posts.count > 0 %>
              <div class="col-md-12">
                <%= render partial: 'posts/post', collection: @user.posts %>
              </div>
          <% else %>
              <div class="col-md-12 text-center">
                <h3 style="color: grey">Nothing yet</h3>
              </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/unfollow.js.erb
$('.unfollow-button').hide();
$('.follow-button').show();

$('.followers-count').text(<%= escape_javascript @user.followers.count.to_s %>);