config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create] do
    member do
      post '/upvote', action: 'upvote'
      post '/downvote', action: 'downvote'
    end
  end

  resources :posts

  post '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote_post'
  post '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote_post'

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users, only: [:new, :create] do
    collection do
      post '/follow/:user_id', action: :follow, as: 'follow'
      post '/unfollow/:user_id', action: :unfollow, as: 'unfollow'
    end
  end

  scope 'u', as: 'public_users' do
    get '/:id', to: 'users#show'
  end

  root 'posts#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  votes      :integer          default(0), not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  include Voteable

  belongs_to :user
  has_many :comments

  validates_presence_of :body
  validates_presence_of :user

  def comments_sorted_by_votes
    self.comments.sort {|c1, c2| c2.votes.count <=> c1.votes.count }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include VotableAction

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :votes)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% @post ||= Post.new %>
<%= form_for(@post) do |f| %>

  <div class="row">
    <div class="col-md-12">
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <br>

    <div class="col-md-12">
      <%= f.submit 'Create', class: 'btn btn-success form-control'  %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div data-id="<%= post.id %>" class="row post">

  <div class="col-md-12">
  <div class="row">
    <div class="col-md-1">
      <%= gravatar_for post.user, {size: 60} %>
    </div>

    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">
          <h3><%= post.user.full_name %></h3>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h5 class="time"><%= post.created_at.strftime('%b %e, %Y @ %l:%M') %></h5>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
     <div class="col-md-11 col-md-offset-1">
       <p class="content"><%= post.body %></p>
     </div>
  </div>

  <div class="row vote-cell" data-id="<%= post.id %>">

    <div class="col-md-1 col-md-offset-1">
      <%= button_to '+', upvote_post_path(post), remote: true, class: 'upvote-button btn btn-success form-control' %>
    </div>

    <div class="col-md-2">
      <h4>Votes <span class="vote-count"><%= post.votes.count %></span></h4>
    </div>

    <div class="col-md-1">
      <%= button_to '-', downvote_post_path(post), remote: true, class: 'downvote-button btn btn-danger form-control' %>
    </div>

    <div class="col-md-4 col-offset-md-2">
      <%= link_to "Comments #{post.comments.count}", post %>
    </div>
  </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="post_container">
  <h1 class="text-center">Feed</h1>

  <% if current_user %>
      <%= link_to 'New Post', '#', class: 'new-post-link btn btn-success pull-right', data: {toggle: 'popover', placement: 'left', html: true, content: render(partial: 'posts/form').gsub(/"/, '\'').html_safe } %>
  <% end %>

  <br>

  <% if current_user %>
    <%= render partial: 'post', collection: current_user.feed %>

  <% else %>
    <h2>Log in or sign up to see more</h2>

  <% end  %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="post_container">
    <%= render partial: 'posts/post', object: @post %>
</div>

<div id="comments">
  <%= render partial: 'comments/comment', collection: @post.comments_sorted_by_votes %>
</div>

<% if current_user %>
    <%= render partial: 'comments/form', locals: {post: @post, comment: @comment} %>
<% end %>

app/views/posts/upvote.js.erb
/**
 * Created by danielward on 6/23/15.
 */

$('#post_container div[data-id="<%= @entity.id %>"].vote-cell span.vote-count').text('<%= escape_javascript(@entity.votes.count.to_s) %>');