config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create] do
    member do
      post '/upvote', action: 'upvote'
      post '/downvote', action: 'downvote'
    end
  end

  resources :posts

  post '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote_post'
  post '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote_post'

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users, only: [:new, :create] do
    collection do
      post '/follow/:user_id', action: :follow, as: 'follow'
      post '/unfollow/:user_id', action: :unfollow, as: 'unfollow'
    end
  end

  scope 'u', as: 'public_users' do
    get '/:id', to: 'users#show'
  end

  root 'posts#index'

end

app/views/common/_account_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">AWESOME SITE</a>
    </div>

    <% if current_user %>
        <%= link_to '<span id="sign_out_button" class="glyphicon glyphicon-log-out"></span>'.html_safe , session_logout_path, method: :delete, class: 'navbar-text navbar-right sign-button-wrapper' %>
        <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link"><%= current_user.full_name %></a> <%= gravatar_for current_user, { size: 30 } %></p>
    <% else %>
        <%= link_to 'Login', session_login_path, class: 'navbar-text navbar-right login-button' %>
        <%= link_to 'Signup', new_user_path, class: 'navbar-text navbar-right' %>
    <% end %>

  </div>
</nav>

app/views/common/_flash_message.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>